using System.Text;

namespace FabricCsharp.Transpiler.JavaGenerator;

/// <summary>
/// Writes formatted Java source code with proper indentation, imports management,
/// and C# source mapping annotations.
/// </summary>
public class JavaWriter : IDisposable
{
    private readonly StringBuilder _sb = new();
    private readonly HashSet<string> _imports = new();
    private int _indentLevel;
    private string _currentPackage = string.Empty;

    private const string IndentString = "    "; // 4 spaces (Java convention)

    public JavaWriter()
    {
        // Default header
        _sb.AppendLine("// Generated by FabricCsharp — do not edit manually");
        _sb.AppendLine();
    }

    /// <summary>
    /// Sets the package for this Java file.
    /// </summary>
    public void WritePackage(string packageName)
    {
        _currentPackage = packageName;
        _sb.AppendLine($"package {packageName};");
        _sb.AppendLine();
    }

    /// <summary>
    /// Adds a Java import. Duplicates and imports from the current package are ignored.
    /// </summary>
    public void AddImport(string importType)
    {
        if (!string.IsNullOrEmpty(importType) && importType.IndexOf('.') > 0)
        {
            _imports.Add(importType);
        }
    }

    /// <summary>
    /// Writes the collected imports to the output.
    /// </summary>
    public void WriteImports()
    {
        foreach (var import in _imports.OrderBy(i => i))
        {
            _sb.AppendLine($"import {import};");
        }

        if (_imports.Count > 0)
            _sb.AppendLine();
    }

    /// <summary>
    /// Emits a C# source mapping comment, visible in generated Java for debugging.
    /// </summary>
    public void WriteSourceMap(string csFilePath, int csLineNumber)
    {
        var fileName = Path.GetFileName(csFilePath);
        _sb.AppendLine($"// C# source: {fileName}:{csLineNumber}");
    }

    /// <summary>
    /// Writes a line with current indentation.
    /// </summary>
    public void WriteLine(string text = "")
    {
        if (text.Length > 0)
            _sb.AppendLine($"{GetIndent()}{text}");
        else
            _sb.AppendLine();
    }

    /// <summary>
    /// Writes a line without trailing newline (for starting blocks, etc.).
    /// </summary>
    public void Write(string text)
    {
        _sb.Append($"{GetIndent()}{text}");
    }

    /// <summary>
    /// Writes raw text without indentation.
    /// </summary>
    public void WriteRaw(string text)
    {
        _sb.Append(text);
    }

    /// <summary>
    /// Increases indentation level by 1.
    /// </summary>
    public void Indent() => _indentLevel++;

    /// <summary>
    /// Decreases indentation level by 1.
    /// </summary>
    public void Outdent()
    {
        if (_indentLevel > 0)
            _indentLevel--;
    }

    /// <summary>
    /// Writes an opening brace and increases indentation.
    /// </summary>
    public void OpenBrace(string? prefix = null)
    {
        if (prefix != null)
            WriteLine($"{prefix} {{");
        else
            WriteLine("{");
        Indent();
    }

    /// <summary>
    /// Decreases indentation and writes a closing brace.
    /// </summary>
    public void CloseBrace(string? suffix = null)
    {
        Outdent();
        if (suffix != null)
            WriteLine($"}}{suffix}");
        else
            WriteLine("}");
    }

    /// <summary>
    /// Returns the complete generated Java source code.
    /// </summary>
    public override string ToString() => _sb.ToString();

    /// <summary>
    /// Saves the generated code to a file.
    /// </summary>
    public async Task SaveAsync(string filePath, CancellationToken ct = default)
    {
        var dir = Path.GetDirectoryName(filePath);
        if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
            Directory.CreateDirectory(dir);

        await File.WriteAllTextAsync(filePath, _sb.ToString(), ct);
    }

    public void Dispose()
    {
        // Nothing to dispose — StringBuilder is managed
    }

    private string GetIndent() => string.Concat(Enumerable.Repeat(IndentString, _indentLevel));
}
